version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - skip: true

release:
  github:
    owner: marianozunino
    name: selfupdater
  name_template: "{{.ProjectName}} v{{.Version}}"
  disable: false


# Publish to go module proxy
publishers:
  - name: gomod
    cmd: go list -m "{{.Module}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
